TagalogWebTest/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TagalogWebTest.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TagalogWebTest/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TagalogWebTest.Pages
{
    public class IndexModel : PageModel
    {


        private readonly ILogger<IndexModel> _logger;
        
        public Dictionary<string, List<TagalogListItem>> OurList { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string SelectedList { get; set; }

        [BindProperty(SupportsGet = true)]
        public DifficultyLevel DifficultyLevel { get; set; }
        
        [BindProperty]
        public string SessionData { get; set; }

        public List<TagalogListItem> Questions { get; set; }

        [BindProperty]
        public string QuestionAnswer { get; set; }
        public string AnswerResponse { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            Init();
            if (!string.IsNullOrEmpty(SelectedList))
            {
                Questions = OurList[SelectedList];
                Questions = Questions.OrderBy(x=> Guid.NewGuid()).ToList();
                SessionData = Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(Questions)));
            }
        }

        private void Init()
        {
            string path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            if (System.IO.File.Exists(Path.Combine(path,"TagalogTest.json")))
            {
                OurList =
                    JsonSerializer.Deserialize<Dictionary<string, List<TagalogListItem>>>(System.IO.File.ReadAllText(Path.Combine(path,"TagalogTest.json")));
            }
        }

        public IActionResult OnPostStartTestAsync()
        {
            return RedirectToPage("Index", new {SelectedList, DifficultyLevel});
        }
        
        public IActionResult OnPostAnswerAsync()
        {
            Questions = JsonSerializer.Deserialize<List<TagalogListItem>>(
                Encoding.UTF8.GetString(Convert.FromBase64String(SessionData)));

            if (QuestionAnswer?.Equals((DifficultyLevel == DifficultyLevel.Easy
                    ? Questions.First().English
                    : Questions.First().Tagalog), StringComparison.CurrentCultureIgnoreCase) ?? false)
            {
                AnswerResponse = "Great job, you are rocking this.";
                Questions.RemoveAt(0);
            }
            else
            {
                AnswerResponse = $"Oops, {Questions.First().Tagalog}: {Questions.First().English} - That's going to cost ya big time.";
                Questions.Add(Questions.First());
                Questions = Questions.OrderBy(x => Guid.NewGuid()).ToList();
            }

            ModelState.Clear();
            Init();
            SessionData = Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(Questions)));
            QuestionAnswer = "";
            return Page();
        }
    }

    public enum DifficultyLevel
    {
        Easy,
        Hard
    }
}

TagalogWebTest/Pages/Lists.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TagalogWebTest.Pages
{
    public class Lists
    {
    }

    public class TagalogListItem
    {
        public string Tagalog { get; set; }
        public string English { get; set; }

        public TagalogListItem(){}
        public TagalogListItem(string tagalog, string english)
        {
            Tagalog = tagalog;
            English = english;
        }
    }


}

TagalogWebTest/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TagalogWebTest.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TagalogWebTest/Pages/Index.cshtml
@page "{SelectedList?}/{DifficultyLevel?}/"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="text-center" style="font-size: 18pt;">
        <h1 class="display-4" style="font-size: larger; font-weight: bold; color: chocolate;">Welcome To the Tagalog Trainer Web App</h1>
        <form method="post">

            @if (string.IsNullOrEmpty(Model.SelectedList))
            {
                <label asp-for="SelectedList">Select a list</label>
                <select asp-for="SelectedList">
                    <option value=""></option>
                    @foreach (var item in Model.OurList.Keys.OrderBy(x => x))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <br />
                <label asp-for="DifficultyLevel">Select Difficulty Level</label>
                @foreach (var item in Enum.GetValues(typeof(DifficultyLevel)).OfType<DifficultyLevel>())
                {
                    <input id="@($"DL_{item.ToString()}")" type="radio" asp-for="DifficultyLevel" value="@item" />
                    <label for="@($"DL_{item.ToString()}")">@item</label>
                }
                <br />
                <button asp-page-handler="StartTest">Start Test</button>
            }
            else if (!Model.Questions.Any())
            {
                <div style="font-weight: bold; padding: 1em; color: green;">You have completed all the questions!</div>
                <label asp-for="SelectedList">Select a list</label>
                <select asp-for="SelectedList">
                    <option value=""></option>
                    @foreach (var item in Model.OurList.Keys.OrderBy(x => x))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <br />
                <label asp-for="DifficultyLevel">Select Difficulty Level</label>
                @foreach (var item in Enum.GetValues(typeof(DifficultyLevel)).OfType<DifficultyLevel>())
                {
                    <input id="@($"DL_{item.ToString()}")" type="radio" asp-for="DifficultyLevel" value="@item" />
                    <label for="@($"DL_{item.ToString()}")">@item</label>
                }
                <br />
                <button asp-page-handler="StartTest">Start Test</button>
            }
            else
            {
                @Html.HiddenFor(x => x.SessionData);
                @if (!string.IsNullOrEmpty(Model.AnswerResponse))
                {
                    <strong>@Model.AnswerResponse</strong>
                    <br /><br />
                }
                <label asp-for="QuestionAnswer">
                    @(Model.DifficultyLevel == DifficultyLevel.Easy
                           ? $"What is \"{Model.Questions.First().Tagalog}\" in English?"
                           : $"What is {Model.Questions.First().English} in Tagalog?")
                </label>
                <input type="text" asp-for="QuestionAnswer" autocomplete="off"/>
                <br />
                <button asp-page-handler="Answer">Submit Answer</button>
            }

        </form>

    </div>

TagalogWebTest/Pages/Lists.cshtml
@page
@{
    ViewData["Title"] = "Lists";
}

<h1>Lists</h1>

TagalogWebTest/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TagalogWebTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Lists">Manage Lists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TagalogWebTest - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>